### ISSUE TITLE
Fatal error: SWIFT TASK CONTINUATION MISUSE

### ISSUE THREAD

**Issue by ismyhc** [cnixbtc/NostrKit#2]
Looks like there is an issue in connect function of Relay.

Here's what Im seeing.

> _Concurrency/CheckedContinuation.swift:184: Fatal error: SWIFT TASK CONTINUATION MISUSE: connect() tried to resume its continuation more than once, throwing socketError(nil)!

This happens after being connected for a few minutes. Basically start a relay and sub and leave it for a bit.

![Screenshot 2022-10-30 at 10 40 44 AM](https://user-images.githubusercontent.com/840551/198885619-02ba334e-7735-4b28-aef2-3def30606d92.png)

![Screenshot 2022-10-30 at 10 40 55 AM](https://user-images.githubusercontent.com/840551/198885634-b655c8b8-bacd-41dd-91c9-6dc159350c93.png)

Will try and dig in a bit myself today when I have a moment, but just wanted to let you know.

**Comment by ismyhc** [comment]
I don know alot about starscream, but I'm playing around with this a bit and the problem here is that you can only call **continuation.resume** once. So I think what you'd need is another delegate method **ondisconnect** and then call that instead on disconnect.

Im also wondering why the socket is disconnecting after a few min. I thought that starscream automatically did a ping loop to keep connection alive.

I'll keep playing around. I've forked the repo and will try and fix what's going on. Will do a pull request.

**Comment by ismyhc** [comment]
Ive created a pull request here: https://github.com/cnixbtc/NostrKit/pull/3

**Comment by cnixbtc** [comment]
Oh yeah that's definitely an issue @ismyhc. Thanks for reporting and submitting a fix right away. 🧡 

Speaking of: I'm not too sure if it even makes sense to include the `Relay` part in the package. Maybe it'd be better to only provide the datatypes, serialization, and signing functionality and leave socket handling up to the user. 🤔 Any thoughts on that?

**Comment by ismyhc** [comment]
> Oh yeah that's definitely an issue @ismyhc. Thanks for reporting and submitting a fix right away. 🧡 
> 
> 
> 
> Speaking of: I'm not too sure if it even makes sense to include the `Relay` part in the package. Maybe it'd be better to only provide the datatypes, serialization, and signing functionality and leave socket handling up to the user. 🤔 Any thoughts on that?

You know I'm glad you mentioned that as the more I'm using I'm realizing that it might be better to let the implementer handle the socket side of things. I'm definitely in agreement.

**Comment by cnixbtc** [comment]
Cool, let's merge your fix in #3 anyway. I'll then move the `Relay` part out of the package and into the example code.

**Comment by ismyhc** [comment]
> Cool, let's merge your fix in #3 anyway. I'll then move the `Relay` part out of the package and into the example code.

Yeah, on my side id actually like to try and use **URLSessions** **webSocketTask**, removing the **starscream** dependency. **webSocketTask** is a little weird to use, but it would work well.

**Comment by cnixbtc** [comment]
Sounds good. I mean you can already do that, no need to use the provided `Relay`, all the types you need are public as well. I'll still remove the Relay part to minimize confusion, though.

**Comment by cnixbtc** [comment]
Removed the `Relay` code and the Starscream dependency in [v1.0.0](https://github.com/cnixbtc/NostrKit/releases/tag/v1.0.0). Let me know how it goes with using `URLSession` and thanks for you help @ismyhc! 🚀

**Comment by ismyhc** [comment]
> Removed the `Relay` code and the Starscream dependency in [v1.0.0](https://github.com/cnixbtc/NostrKit/releases/tag/v1.0.0). Let me know how it goes with using `URLSession` and thanks for you help @ismyhc! 🚀

Oh nice!! Will definitely do. I like how you did this by the way. Creating the messages ready to be sent by socket. Im doing some front end stuff with the previous lib state, but as soon as that's done, Ill switch out the old Relay code and re-write the sockets using **URLSession**
